-- 投资项目表
CREATE TABLE tb_project (
  invest_id bigint NOT NULL AUTO_INCREMENT COMMENT '项目id',
  invest_name varchar(200) NOT NULL COMMENT '项目名称',
  abbreviation varchar(100) COMMENT '项目简称',
  project_describe text COMMENT '项目描述',
  project_type int COMMENT '项目类型（1:固定金额投资,2:众筹）',
  type_id bigint COMMENT '分类id',
  cycle int COMMENT '周期(天)',
  cycle_type int COMMENT '回款方式（1:到期返还,2:每日返利）',
  conversion varchar(20) COMMENT '日收益率(%)',
  scale_amount bigint COMMENT '项目规模金额(个人购买)',
  invest_repeat int COMMENT '可买台数',
  principal_profit bigint COMMENT '每日收益，（每日返还才有）',
  total_profit bigint COMMENT '总收益 =每日收益 * 周期',
  total_cost bigint COMMENT '本金+收益 = 投资金额 + 每日收益 * 周期',
  img varchar(500) COMMENT '设备图片',
  sort int DEFAULT 0 COMMENT '排序',
  status int DEFAULT 1 COMMENT '上下架 0下架  1上架   2 删除',
  rushbuy_falg int DEFAULT 0 COMMENT '是否限时抢购 1是，0不是',
  hour int COMMENT '限时抢购几个小时',
  rushbuy_start varchar(50) COMMENT '限时抢购开始时间',
  rushbuy_end varchar(50) COMMENT '限时抢购结束时间',
  rushbuy_start_time bigint COMMENT '限时抢购开始时间戳',
  rushbuy_end_time bigint COMMENT '限时抢购结束时间戳',
  rushbuy_num int COMMENT '限时可抢份数',
  rushbuy_remain_num int COMMENT '限时可抢剩余份数',
  expire varchar(50) COMMENT '抢购结束时间，从上架那一刻算，上架的时间加上抢购时间',
  rush_week int COMMENT '一级市场开放周几',
  rush_hour int COMMENT '一级市场开放时间',
  rush_minute int COMMENT '一级市场可抢购时间',
  market_date varchar(50) COMMENT '二级市场开放时间',
  register_start_date varchar(50) COMMENT '注册起始时间',
  register_end_date varchar(50) COMMENT '注册结束时间',
  sj_date varchar(50) COMMENT '指定上架日期',
  xj_date varchar(50) COMMENT '指定下架日期',
  return_principal int DEFAULT 0 COMMENT '是否立返本金',
  return_project int DEFAULT 0 COMMENT '是否立返项目',
  return_ratio decimal(10,4) COMMENT '返还比例',
  return_to int COMMENT '返还到谁',
  return_wheel int DEFAULT 0 COMMENT '是否返还转盘次数',
  return_wheel_to int COMMENT '返还转盘次数给本人',
  return_wheel_to_sup int COMMENT '返还转盘次数给上级',
  coupon_id bigint COMMENT '赠送优惠券id',
  coupon_name varchar(100) COMMENT '优惠券名称',
  discount varchar(50) COMMENT '折扣',
  discount_start varchar(50) COMMENT '折扣开始时间',
  discount_end varchar(50) COMMENT '折扣结束时间',
  discount_num int COMMENT '折扣数量',
  discount_vip int COMMENT '折扣VIP',
  group_time int COMMENT '团购时间',
  group_leader_rebate int COMMENT '团长返利',
  group_member_rebate int COMMENT '团员返利',
  join_num int DEFAULT 0 COMMENT '参与人数',
  member_registration_time int COMMENT '会员注册时间',
  vip int COMMENT 'VIP等级',
  task_limit_time varchar(50) COMMENT '任务限制时间',
  dis_flag int COMMENT 'disFlag',
  return_invest bigint COMMENT 'returnInvest',
  return_project_to int COMMENT 'returnProjectTo',
  return_project_to_sup int COMMENT 'returnProjectToSup',
  return_ratio_sup decimal(10,4) COMMENT 'returnRatioSup',
  return_to_sup int COMMENT 'returnToSup',
  ret_to int COMMENT 'retTo',
  create_date datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_date datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (invest_id),
  KEY idx_status (status),
  KEY idx_sort (sort),
  KEY idx_type_id (type_id),
  KEY idx_project_type (project_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='投资项目表';

-- 插入测试数据
INSERT INTO tb_project (
  invest_name, abbreviation, project_describe, project_type, type_id, 
  cycle, cycle_type, conversion, scale_amount, invest_repeat,
  principal_profit, total_profit, total_cost, img, sort, status
) VALUES 
('稳健理财项目A', '稳健A', '低风险稳健收益项目，适合保守型投资者', 1, 1, 
 30, 2, '0.5', 10000, 5,
 50, 1500, 11500, '/images/project1.jpg', 1, 1),
('高收益项目B', '高收益B', '中等风险高收益项目，适合激进型投资者', 1, 2, 
 60, 1, '1.2', 20000, 3,
 240, 14400, 34400, '/images/project2.jpg', 2, 1),
('众筹项目C', '众筹C', '创新型众筹项目，支持创业企业发展', 2, 3, 
 90, 2, '0.8', 50000, 2,
 400, 36000, 86000, '/images/project3.jpg', 3, 1);
