-- 测试我的投资功能
-- 执行时间: 2024年

-- 1. 创建投资记录表（如果不存在）
-- CREATE TABLE IF NOT EXISTS `tb_investment_record` (
--   `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
--   `user_id` bigint(20) NOT NULL COMMENT '用户ID',
--   `project_id` bigint(20) NOT NULL COMMENT '项目ID',
--   `investment_amount` bigint(20) NOT NULL COMMENT '投资金额(分)',
--   `order_id` bigint(20) NOT NULL COMMENT '订单ID',
--   `order_abbr` varchar(50) DEFAULT NULL COMMENT '订单号简称',
--   `order_date` datetime NOT NULL COMMENT '投资日期',
--   `profit_amount` bigint(20) DEFAULT 0 COMMENT '收益金额(分)',
--   `profit_date` datetime DEFAULT NULL COMMENT '收益日期',
--   `profit_interest` bigint(20) DEFAULT 0 COMMENT '收益利息(分)',
--   `profit_principal` bigint(20) DEFAULT 0 COMMENT '收益本金(分)',
--   `status` tinyint(4) DEFAULT 0 COMMENT '状态 0:未收益 1:已收益',
--   `cycle` int(11) DEFAULT NULL COMMENT '项目周期',
--   `cycle_type` tinyint(4) DEFAULT 1 COMMENT '周期类型 1:到期收益含本金 2:每日返本金到期收益',
--   `ddsy` bigint(20) DEFAULT 0 COMMENT '等待收益(分)',
--   `invest_count` int(11) DEFAULT 1 COMMENT '投资次数',
--   `rush_minute` int(11) DEFAULT 0 COMMENT '抢购分钟数',
--   `agent` varchar(100) DEFAULT NULL COMMENT '代理',
--   `salesmanid` varchar(50) DEFAULT NULL COMMENT '销售员ID',
--   `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
--   `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
--   PRIMARY KEY (`id`),
--   KEY `idx_user_id` (`user_id`),
--   KEY `idx_project_id` (`project_id`),
--   KEY `idx_status` (`status`),
--   KEY `idx_order_date` (`order_date`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='投资记录表';

-- 2. 创建项目表（如果不存在）
-- CREATE TABLE IF NOT EXISTS `tb_project` (
--   `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
--   `name` varchar(200) NOT NULL COMMENT '项目名称',
--   `img` varchar(500) DEFAULT NULL COMMENT '项目图片',
--   `status` tinyint(4) DEFAULT 1 COMMENT '项目状态',
--   `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目表';

-- 3. 插入测试数据
-- INSERT INTO `tb_project` (`name`, `img`) VALUES 
-- ('新能源投资项目A', 'https://example.com/project1.jpg'),
-- ('科技创新基金B', 'https://example.com/project2.jpg'),
-- ('绿色环保项目C', 'https://example.com/project3.jpg');

-- INSERT INTO `tb_investment_record` (
--   `user_id`, `project_id`, `investment_amount`, `order_id`, `order_abbr`, 
--   `order_date`, `profit_amount`, `profit_date`, `profit_interest`, 
--   `profit_principal`, `status`, `cycle`, `cycle_type`, `ddsy`, 
--   `invest_count`, `rush_minute`, `agent`, `salesmanid`
-- ) VALUES 
-- (1, 1, 1000000, 1001, 'INV001', '2024-01-15 10:00:00', 50000, '2024-02-15 10:00:00', 50000, 1000000, 1, 30, 1, 0, 1, 0, '代理A', 'SALES001'),
-- (1, 2, 2000000, 1002, 'INV002', '2024-01-20 14:30:00', 0, NULL, 0, 0, 0, 60, 2, 100000, 1, 0, '代理B', 'SALES002'),
-- (1, 3, 1500000, 1003, 'INV003', '2024-01-25 16:45:00', 0, NULL, 0, 0, 0, 45, 1, 75000, 1, 0, '代理C', 'SALES003');

-- 4. 测试我的投资接口
-- 接口地址: GET /api/grzx/myprofit
-- 需要登录状态（Authorization: Bearer {token}）
-- 请求参数: limit, page, status

-- 5. 测试用例
-- 查询正在生产的投资（status=0）:
-- GET /api/grzx/myprofit?limit=10&page=1&status=0

-- 查询已完成的投资（status=1）:
-- GET /api/grzx/myprofit?limit=10&page=1&status=1

-- 6. 预期返回数据格式
-- {
--     "code": 0,
--     "data": {
--         "list": [
--             {
--                 "id": 1,
--                 "userId": 1,
--                 "investId": 1,
--                 "investName": "新能源投资项目A",
--                 "img": "https://example.com/project1.jpg",
--                 "investmentAmount": 1000000,
--                 "orderId": 1001,
--                 "orderAbbr": "INV001",
--                 "orderDate": "2024-01-15 10:00:00",
--                 "profitAmount": 50000,
--                 "profitDate": "2024-02-15 10:00:00",
--                 "profitInterest": 50000,
--                 "profitPrincipal": 1000000,
--                 "status": 1,
--                 "cycle": 30,
--                 "cycleType": 1,
--                 "ddsy": 0,
--                 "investCount": 1,
--                 "rushMinute": 0,
--                 "agent": "代理A",
--                 "salesmanid": "SALES001",
--                 "mobile": "13800138000"
--             }
--         ],
--         "sum": {},
--         "total": 3
--     },
--     "msg": ""
-- }

-- 7. 注意事项
-- - 用户必须已登录（需要有效的token）
-- - status参数：0表示正在生产，1表示生产结束
-- - 金额单位是分，需要在前端转换为元
-- - 日期格式为yyyy-MM-dd HH:mm:ss
-- - 建议添加缓存机制提高查询性能
-- - 可以考虑添加投资统计汇总功能
