-- 用户表结构优化 - 使用上级ID作为外键关联
DROP TABLE IF EXISTS `tb_user`;

CREATE TABLE `tb_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `password` varchar(100) NOT NULL COMMENT '密码',
  `two_pwd` varchar(100) DEFAULT NULL COMMENT '二级密码',
  `invite_code` varchar(50) DEFAULT NULL COMMENT '邀请码',
  `superior_id` bigint(20) DEFAULT NULL COMMENT '上级用户ID（外键关联）',
  `agent` varchar(100) DEFAULT NULL COMMENT '代理信息',
  `agent_name` varchar(100) DEFAULT NULL COMMENT '代理名称',
  `salesmanid` varchar(50) DEFAULT NULL COMMENT '业务员ID',
  `salesman_name` varchar(100) DEFAULT NULL COMMENT '业务员名称',
  `channel` varchar(50) DEFAULT NULL COMMENT '客户渠道号',
  `equipment` tinyint(4) DEFAULT NULL COMMENT '登录端口(1:安卓, 2:ios, 3:pc, 4:未知)',
  `register_ip` varchar(50) DEFAULT NULL COMMENT '注册IP',
  `last_ip` varchar(50) DEFAULT NULL COMMENT '最后登录IP',
  `last_date` datetime DEFAULT NULL COMMENT '最后登录时间',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `extension_name` varchar(100) DEFAULT NULL COMMENT '推广名称',
  `today_investment` bigint(20) DEFAULT 0 COMMENT '今日投资',
  `history_investment` bigint(20) DEFAULT 0 COMMENT '历史投资',
  `today_profit` bigint(20) DEFAULT 0 COMMENT '今日收益',
  `history_profit` bigint(20) DEFAULT 0 COMMENT '历史收益',
  `today_recharge` bigint(20) DEFAULT 0 COMMENT '今日充值',
  `today_withdraw` bigint(20) DEFAULT 0 COMMENT '今日提现',
  `today_recharge_cnt` bigint(20) DEFAULT 0 COMMENT '今日充值次数',
  `today_withdraw_cnt` bigint(20) DEFAULT 0 COMMENT '今日提现次数',
  `charge_sum` bigint(20) DEFAULT 0 COMMENT '累计充值',
  `withdraw_sum` bigint(20) DEFAULT 0 COMMENT '累计提现',
  `historychargecnt` bigint(20) DEFAULT 0 COMMENT '历史充值次数',
  `historywithdrawcnt` bigint(20) DEFAULT 0 COMMENT '历史提现次数',
  `history_coupon_balance` bigint(20) DEFAULT 0 COMMENT '历史优惠券余额',
  `coupon_cnt` bigint(20) DEFAULT 0 COMMENT '优惠券数量',
  `coupon_balance` bigint(20) DEFAULT 0 COMMENT '优惠券余额',
  `history_privilege_cnt` bigint(20) DEFAULT 0 COMMENT '历史特权券数量',
  `privilege_cnt` bigint(20) DEFAULT 0 COMMENT '特权券数量',
  `balance` bigint(20) DEFAULT 0 COMMENT '余额',
  `cashwithdrawable` bigint(20) DEFAULT 0 COMMENT '可提现余额',
  `freeze_balance` bigint(20) DEFAULT 0 COMMENT '冻结余额',
  `uacnt` bigint(20) DEFAULT 0 COMMENT 'U级账户余额',
  `ubcnt` bigint(20) DEFAULT 0 COMMENT 'U级账户余额',
  `uccnt` bigint(20) DEFAULT 0 COMMENT 'U级账户余额',
  `ua_profit` bigint(20) DEFAULT 0 COMMENT 'U级账户收益',
  `ub_profit` bigint(20) DEFAULT 0 COMMENT 'U级账户收益',
  `uc_profit` bigint(20) DEFAULT 0 COMMENT 'U级账户收益',
  `history_ua_profit` bigint(20) DEFAULT 0 COMMENT '历史U级账户收益',
  `history_ub_profit` bigint(20) DEFAULT 0 COMMENT '历史U级账户收益',
  `history_uc_profit` bigint(20) DEFAULT 0 COMMENT '历史U级账户收益',
  `to_daywithdraw_count` bigint(20) DEFAULT 0 COMMENT '今日提现次数',
  `to_daywithdraw_quota` bigint(20) DEFAULT 0 COMMENT '今日提现额度',
  `withdraw_count` bigint(20) DEFAULT 0 COMMENT '提现次数',
  `withdraw_quota` bigint(20) DEFAULT 0 COMMENT '提现额度',
  `commission_balance` bigint(20) DEFAULT 0 COMMENT '佣金余额',
  `tgrs` bigint(20) DEFAULT 0 COMMENT '推广人数',
  `sy_sum` bigint(20) DEFAULT 0 COMMENT '收益总额',
  `to_dayctc` bigint(20) DEFAULT 0 COMMENT '今日CTC',
  `historyctc` bigint(20) DEFAULT 0 COMMENT '历史CTC',
  `status` tinyint(4) DEFAULT 1 COMMENT '状态 0：禁用 1：正常',
  `invite_code_status` tinyint(4) DEFAULT 1 COMMENT '邀请码状态 0：禁用 1：正常',
  `tz_withdraw_status` tinyint(4) DEFAULT 1 COMMENT '投资提现状态 0：禁用 1：正常',
  `reward_withdraw_status` tinyint(4) DEFAULT 1 COMMENT '奖励提现状态 0：禁用 1：正常',
  `biaoqian` varchar(100) DEFAULT NULL COMMENT '标签',
  `vip` tinyint(4) DEFAULT 0 COMMENT 'VIP等级',
  `viplr` bigint(20) DEFAULT 0 COMMENT 'VIP利率',
  `assets` bigint(20) DEFAULT 0 COMMENT '资产',
  `ended_items` bigint(20) DEFAULT 0 COMMENT '已结束项目数',
  `ended_principal` bigint(20) DEFAULT 0 COMMENT '已结束本金',
  `ended_profit` bigint(20) DEFAULT 0 COMMENT '已结束收益',
  `flag` bigint(20) DEFAULT 0 COMMENT '标志',
  `id_card` varchar(20) DEFAULT NULL COMMENT '身份证号',
  `itmes` bigint(20) DEFAULT 0 COMMENT '项目数',
  `jr_profit` bigint(20) DEFAULT 0 COMMENT '今日收益',
  `login_time` varchar(50) DEFAULT NULL COMMENT '登录时间',
  `payment_pwd` varchar(100) DEFAULT NULL COMMENT '支付密码',
  `todaybalance10` bigint(20) DEFAULT 0 COMMENT '今日余额10',
  `todaybalance20` bigint(20) DEFAULT 0 COMMENT '今日余额20',
  `todaybalance5` bigint(20) DEFAULT 0 COMMENT '今日余额5',
  `todaycharge100` bigint(20) DEFAULT 0 COMMENT '今日充值100',
  `todaycharge20` bigint(20) DEFAULT 0 COMMENT '今日充值20',
  `todaycharge50` bigint(20) DEFAULT 0 COMMENT '今日充值50',
  `total_principal` bigint(20) DEFAULT 0 COMMENT '总本金',
  `total_profit` bigint(20) DEFAULT 0 COMMENT '总收益',
  `valid3user` bigint(20) DEFAULT 0 COMMENT '有效3个月用户数',
  `valid6user` bigint(20) DEFAULT 0 COMMENT '有效6个月用户数',
  `valid9user` bigint(20) DEFAULT 0 COMMENT '有效9个月用户数',
  `vip1state` bigint(20) DEFAULT 0 COMMENT 'VIP1状态',
  `vip2state` bigint(20) DEFAULT 0 COMMENT 'VIP2状态',
  `vip3state` bigint(20) DEFAULT 0 COMMENT 'VIP3状态',
  `vip4state` bigint(20) DEFAULT 0 COMMENT 'VIP4状态',
  `vip5state` bigint(20) DEFAULT 0 COMMENT 'VIP5状态',
  `vip6state` bigint(20) DEFAULT 0 COMMENT 'VIP6状态',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`),
  UNIQUE KEY `uk_mobile` (`mobile`),
  UNIQUE KEY `uk_invite_code` (`invite_code`),
  KEY `idx_superior_id` (`superior_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_date` (`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 插入测试数据
INSERT INTO `tb_user` (
  `id`, `username`, `mobile`, `password`, `invite_code`, `superior_id`,
  `agent`, `agent_name`, `salesmanid`, `salesman_name`, `channel`,
  `equipment`, `register_ip`, `last_ip`, `last_date`, `create_date`,
  `extension_name`, `today_investment`, `history_investment`, `today_profit`,
  `history_profit`, `today_recharge`, `today_withdraw`, `today_recharge_cnt`,
  `today_withdraw_cnt`, `charge_sum`, `withdraw_sum`, `historychargecnt`,
  `historywithdrawcnt`, `history_coupon_balance`, `coupon_cnt`, `coupon_balance`,
  `history_privilege_cnt`, `privilege_cnt`, `balance`, `cashwithdrawable`,
  `freeze_balance`, `uacnt`, `ubcnt`, `uccnt`, `ua_profit`, `ub_profit`,
  `uc_profit`, `history_ua_profit`, `history_ub_profit`, `history_uc_profit`,
  `to_daywithdraw_count`, `to_daywithdraw_quota`, `withdraw_count`, `withdraw_quota`,
  `commission_balance`, `tgrs`, `sy_sum`, `to_dayctc`, `historyctc`, `status`,
  `invite_code_status`, `tz_withdraw_status`, `reward_withdraw_status`, `biaoqian`,
  `vip`, `viplr`, `assets`, `ended_items`, `ended_principal`, `ended_profit`,
  `flag`, `id_card`, `itmes`, `jr_profit`, `login_time`, `payment_pwd`,
  `todaybalance10`, `todaybalance20`, `todaybalance5`, `todaycharge100`,
  `todaycharge20`, `todaycharge50`, `total_principal`, `total_profit`,
  `valid3user`, `valid6user`, `valid9user`, `vip1state`, `vip2state`,
  `vip3state`, `vip4state`, `vip5state`, `vip6state`
) VALUES (
  1, 'testuser', '13800138000', '$2a$10$7JB720yubVSOfvVWdBYoOeymFQJwq1VxqM9aMhMp2EqT7HxWnz6Oe',
  'TEST001', NULL, '代理A', '代理A名称', 'S001', '业务员A', '渠道A',
  1, '192.168.1.1', '192.168.1.1', NOW(), NOW(), '推广A',
  1000000, 5000000, 50000, 250000, 200000, 100000, 2, 1,
  1000000, 500000, 5, 3, 10000, 2, 5000, 1, 1,
  1000000, 800000, 0, 100000, 200000, 300000, 10000, 20000, 30000,
  5000, 10000, 15000, 1, 1, 100000, 200000, 300000, 50000,
  100000, 150000, 1, 1, 1, 1, 'VIP用户', 1, 500,
  1000000, 5, 500000, 250000, 1, '110101199001011234', 10,
  50000, NOW(), '123456', 100000, 200000, 50000, 1000000, 500000,
  250000, 5000000, 250000, 3, 2, 1, 1, 0, 0, 0, 0, 0
);

-- 插入上级用户数据
INSERT INTO `tb_user` (
  `id`, `username`, `mobile`, `password`, `invite_code`, `superior_id`,
  `agent`, `agent_name`, `salesmanid`, `salesman_name`, `channel`,
  `equipment`, `register_ip`, `last_ip`, `last_date`, `create_date`,
  `extension_name`, `balance`, `status`, `invite_code_status`
) VALUES (
  2, 'superioruser', '13800138001', '$2a$10$7JB720yubVSOfvVWdBYoOeymFQJwq1VxqM9aMhMp2EqT7HxWnz6Oe',
  'SUPER001', NULL, '代理B', '代理B名称', 'S002', '业务员B', '渠道B',
  1, '192.168.1.2', '192.168.1.2', NOW(), NOW(), '推广B',
  2000000, 1, 1
);

-- 更新测试用户的上级ID
UPDATE `tb_user` SET `superior_id` = 2 WHERE `id` = 1;
